server:
  port: 8082

spring:
  application:
    name: gateway-service

management:
  endpoints:
    web:
      exposure:
        include: health, info, prometheus, metrics
  endpoint:
    health:
      show-details: when_authorized
      probes:
        enabled: true
    prometheus:
      access: read_only
  prometheus:
    metrics:
      export:
        enabled: true