spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_URI}/realms/${KEYCLOAK_REALM}

  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
