spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_ISSUER_URI}
  datasource:
    url: ${POSTGRE_URL}
    username: ${POSTGRE_USERNAME}
    password: ${POSTGRE_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    database: postgresql
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  ai:
    vertex:
      ai:
        gemini:
          project-id: ${GEMINI_PROJECT_ID}
          location: ${GEMINI_LOCATION}
          chat:
            options:
              model: ${GEMINI_MODEL}
        embedding:
          project-id: ${GEMINI_PROJECT_ID}
          location: ${GEMINI_LOCATION}

    vectorstore:
      pgvector:
        table-name: mindbridge_vector
        initialize-schema: true
logging:
  level:
    org:
      springframework:
        ai:
          chat:
            client: DEBUG


